>>SOURCE FREE

IDENTIFICATION DIVISION.
PROGRAM-ID. HelloName.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 WS-NAME PIC X(30).

PROCEDURE DIVISION.
    DISPLAY "What is your name? " WITH NO ADVANCING.
    ACCEPT WS-NAME.
    DISPLAY "Hello, " FUNCTION TRIM(WS-NAME) "!".
    STOP RUN.
